Histogram
js-tasks-ru/htmlcss-20220317_alexxxusachev888 pull request #6
Opened 2022-03-31 12:10 UTC by alexxxusachev888

Привет, Герман) У меня возникла сложность проставить разную высоту колонок в самой гистограмме (вертикальные блоки). Когда добавлял высоту (height) элемента в процентах через атрибут style непосредственно в теге <div> с блоком, то он исчезал при открытии в браузере. Помоги пожалуйста)

2022-03-31 12:11 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-31 15:20 UTC, GSemikozov requested changes

2022-03-31 15:20 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +@import url('https://fonts.googleapis.com/css2?family=Inter&display=swap');
шрифты подключаем не внутри каждого компонента отдельно, а глобально, для этого у нас есть fonts.css

2022-03-31 15:20 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.container {
компонент контейнера уже есть (или будет создан, но вне блока .histogram)

2022-03-31 15:20 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 354px;
жестко фиксировать ширину не нужно, можно удалить

2022-03-31 15:20 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin: 16px 24px 0px 24px;
padding

2022-03-31 15:20 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin: 16px 24px 0px 24px;
точнее так: проще 1 раз на уровне блока задать паддинги, чтобы не задавать каждому дочернему элементы однотипные марджины)
*исправить везде ниже

2022-03-31 15:20 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin: 16px 24px 0px 24px;
по дизайну у этого элемента только margin-bottom: 6px

2022-03-31 15:20 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin: 6px 268px 0px 24px;
а здесь margin-bottom: 39px

2022-03-31 15:20 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__text1 {
не информативный класс, можно например .histogram__text1 -> .histogram__title, .histogram__text2 -> .histogram__link

2022-03-31 15:20 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin: 39px 24px 24px 24px;
39 либо здесь, либо на уровне __box, остальные не нужны

2022-03-31 15:20 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 9px;
лучше как мы и говорили на занятии - flex-basis: 9px + flex-grow: 1 (проверить что будет если оставить 1-2 колонки)

2022-04-02 11:04 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-03 18:20 UTC, GSemikozov requested changes

2022-04-03 18:20 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__rectangles_point {
.histogram__rectangles_point -> .histogram__rectangles-point

2022-04-03 18:20 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 50px;
высота задается на уровне .histogram__rectangles, чтобы высоту .histogram__rectangles-point задавать в процентах

2022-04-05 13:59 UTC, alexxxusachev888 commented on 04-lection2/01-histogram/histogram.css
> +    height: 50px;
Спасибо, правки внес

2022-04-13 20:43 UTC, GSemikozov approved these changes

2022-04-13 20:43 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2022-04-13 20:44 UTC, GSemikozov approved these changes

2022-04-13 20:44 UTC, merged